package com.apollo.console.demo.bean;

import java.math.BigDecimal;
import java.util.Date;

public class CompInst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.COMP_INST_ID
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private Long compInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.COMP_ID
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.STRATEGY_ID
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private Long strategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.COMP_INST_NAME
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private String compInstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.COMP_INST_DESC
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private String compInstDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.COMP_INST_CFG_STATUS
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private BigDecimal compInstCfgStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.CREATOR
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.CREATE_DATE
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.MODIFIER
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.MODIFY_DATE
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.DATA_STATE
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private BigDecimal dataState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.START_TIME
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.END_TIME
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMP_INST.COMP_INST_RUN_STATUS
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    private BigDecimal compInstRunStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.COMP_INST_ID
     *
     * @return the value of COMP_INST.COMP_INST_ID
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public Long getCompInstId() {
        return compInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.COMP_INST_ID
     *
     * @param compInstId the value for COMP_INST.COMP_INST_ID
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setCompInstId(Long compInstId) {
        this.compInstId = compInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.COMP_ID
     *
     * @return the value of COMP_INST.COMP_ID
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.COMP_ID
     *
     * @param compId the value for COMP_INST.COMP_ID
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.STRATEGY_ID
     *
     * @return the value of COMP_INST.STRATEGY_ID
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public Long getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.STRATEGY_ID
     *
     * @param strategyId the value for COMP_INST.STRATEGY_ID
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setStrategyId(Long strategyId) {
        this.strategyId = strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.COMP_INST_NAME
     *
     * @return the value of COMP_INST.COMP_INST_NAME
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public String getCompInstName() {
        return compInstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.COMP_INST_NAME
     *
     * @param compInstName the value for COMP_INST.COMP_INST_NAME
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setCompInstName(String compInstName) {
        this.compInstName = compInstName == null ? null : compInstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.COMP_INST_DESC
     *
     * @return the value of COMP_INST.COMP_INST_DESC
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public String getCompInstDesc() {
        return compInstDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.COMP_INST_DESC
     *
     * @param compInstDesc the value for COMP_INST.COMP_INST_DESC
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setCompInstDesc(String compInstDesc) {
        this.compInstDesc = compInstDesc == null ? null : compInstDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.COMP_INST_CFG_STATUS
     *
     * @return the value of COMP_INST.COMP_INST_CFG_STATUS
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public BigDecimal getCompInstCfgStatus() {
        return compInstCfgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.COMP_INST_CFG_STATUS
     *
     * @param compInstCfgStatus the value for COMP_INST.COMP_INST_CFG_STATUS
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setCompInstCfgStatus(BigDecimal compInstCfgStatus) {
        this.compInstCfgStatus = compInstCfgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.CREATOR
     *
     * @return the value of COMP_INST.CREATOR
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.CREATOR
     *
     * @param creator the value for COMP_INST.CREATOR
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.CREATE_DATE
     *
     * @return the value of COMP_INST.CREATE_DATE
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.CREATE_DATE
     *
     * @param createDate the value for COMP_INST.CREATE_DATE
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.MODIFIER
     *
     * @return the value of COMP_INST.MODIFIER
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.MODIFIER
     *
     * @param modifier the value for COMP_INST.MODIFIER
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.MODIFY_DATE
     *
     * @return the value of COMP_INST.MODIFY_DATE
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.MODIFY_DATE
     *
     * @param modifyDate the value for COMP_INST.MODIFY_DATE
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.DATA_STATE
     *
     * @return the value of COMP_INST.DATA_STATE
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public BigDecimal getDataState() {
        return dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.DATA_STATE
     *
     * @param dataState the value for COMP_INST.DATA_STATE
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setDataState(BigDecimal dataState) {
        this.dataState = dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.START_TIME
     *
     * @return the value of COMP_INST.START_TIME
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.START_TIME
     *
     * @param startTime the value for COMP_INST.START_TIME
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.END_TIME
     *
     * @return the value of COMP_INST.END_TIME
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.END_TIME
     *
     * @param endTime the value for COMP_INST.END_TIME
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMP_INST.COMP_INST_RUN_STATUS
     *
     * @return the value of COMP_INST.COMP_INST_RUN_STATUS
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public BigDecimal getCompInstRunStatus() {
        return compInstRunStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMP_INST.COMP_INST_RUN_STATUS
     *
     * @param compInstRunStatus the value for COMP_INST.COMP_INST_RUN_STATUS
     *
     * @mbggenerated Thu Apr 30 16:25:19 CST 2015
     */
    public void setCompInstRunStatus(BigDecimal compInstRunStatus) {
        this.compInstRunStatus = compInstRunStatus;
    }
}